/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class map_jyuntech_cn_tddmap_Model_TextModel */

#ifndef _Included_map_jyuntech_cn_tddmap_Model_TextModel
#define _Included_map_jyuntech_cn_tddmap_Model_TextModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     map_jyuntech_cn_tddmap_Model_TextModel
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_map_jyuntech_cn_tddmap_Model_TextModel_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
